import { babyjubjub } from '@noble/curves/misc.js'
import { blake512 } from '@noble/hashes/blake1.js'

import { poseidonPermute } from '../poseidon/permutation.js'

/**
 * EdDSA-over-BabyJubJub with a Poseidon transcript, as specified by
 * iden3/circomlib and consumed by the RAILGUN circuits.
 *
 * `@noble/curves` deliberately does not provide this scheme. Its exported
 * `babyjubjub.sign`/`getPublicKey` are a *generic* EdDSA wrapper whose upstream
 * docs state it "is not the BabyJubJub stack used by iden3/circomlib" and is
 * "not meant as an interoperability target" for it. Only the curve arithmetic
 * and `blake512` are reused here; the scheme itself is implemented below and
 * pinned by the circomlibjs reference vectors in `test/eddsa.test.ts`.
 */

const Point = babyjubjub.Point

// Prime-order subgroup generator (circomlib's `Base8`). Pinned explicitly
// rather than taken from `Point.BASE` so that a change to noble's choice of
// generator cannot silently alter derived keys.
const BASE8 = /* @__PURE__ */ Point.fromAffine({
  x: 5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  y: 16950150798460657717958625567821834550301663161624707787222815936182638968203n,
})

// Order of the prime-order subgroup generated by Base8.
const SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n

// Base field modulus of BabyJubJub (the BN254 scalar field).
const FIELD_MODULUS =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n

type Affine = { x: bigint; y: bigint }

/**
 * Decode a little-endian byte array as an unsigned integer.
 * @param bytes - Little-endian bytes.
 * @returns The decoded integer.
 */
const bytesToBigIntLE = (bytes: Uint8Array): bigint => {
  let result = 0n
  for (let i = bytes.length - 1; i >= 0; i -= 1) {
    result = (result << 8n) | BigInt(bytes[i]!)
  }
  return result
}

/**
 * Encode an integer as 32 little-endian bytes, truncating above 2^256.
 * @param value - Value to encode.
 * @returns The 32-byte little-endian encoding.
 */
const bigIntToBytesLE32 = (value: bigint): Uint8Array => {
  const bytes = new Uint8Array(32)
  for (let i = 0; i < 32; i += 1) {
    bytes[i] = Number((value >> BigInt(8 * i)) & 0xffn)
  }
  return bytes
}

/**
 * Apply circomlib's `pruneBuffer` clamping to a Blake-512 digest.
 *
 * Note this clamps the *full 64-byte* digest, matching circomlib — the second
 * half is used verbatim as the nonce prefix, so only byte 31 is affected.
 * @param digest - 64-byte Blake-512 digest. Not mutated.
 * @returns A pruned copy of the digest.
 */
const pruneDigest = (digest: Uint8Array): Uint8Array => {
  const pruned = Uint8Array.from(digest)
  pruned[0] = pruned[0]! & 0xf8
  pruned[31] = (pruned[31]! & 0x7f) | 0x40
  return pruned
}

/**
 * Expand a private key into the values the scheme derives from it.
 *
 * The signing scalar `s` is the low half of the pruned digest, but the public
 * key is `Base8·(s >> 3)`. That asymmetry is intrinsic to circomlib — `s`
 * itself (not `s >> 3`) is what appears in the signature equation — and the
 * circuits are built around it.
 * @param privateKey - 32-byte private key.
 * @returns The pruned digest, signing scalar, and public key point.
 */
const expandPrivateKey = (privateKey: Uint8Array) => {
  const digest = pruneDigest(blake512(privateKey))
  const scalar = bytesToBigIntLE(digest.subarray(0, 32))

  // `multiply` is the constant-time ladder; the scalar is secret.
  return {
    digest,
    scalar,
    publicKey: BASE8.multiply((scalar >> 3n) % SUBGROUP_ORDER),
  }
}

/**
 * Decode a field element, rejecting non-canonical (>= p) encodings so that a
 * point has exactly one valid representation.
 * @param value - Candidate field element.
 * @returns True when the value is canonical.
 */
const isCanonicalFieldElement = (value: bigint): boolean =>
  value >= 0n && value < FIELD_MODULUS

/**
 * Derive the BabyJubJub public key for a private key.
 * @param privateKey - 32-byte private key.
 * @returns The public key in affine coordinates.
 */
const derivePublicKey = (privateKey: Uint8Array): Affine =>
  expandPrivateKey(privateKey).publicKey.toAffine()

/**
 * Sign a field-element message under EdDSA-Poseidon.
 * @param privateKey - 32-byte private key.
 * @param message - Message as a BabyJubJub field element.
 * @returns The signature commitment `R8` and scalar `S`.
 */
const signPoseidon = (
  privateKey: Uint8Array,
  message: bigint
): { R8: Affine; S: bigint } => {
  const { digest, scalar, publicKey } = expandPrivateKey(privateKey)

  // Deterministic nonce: the unused half of the key digest, bound to the message.
  const nonceInput = new Uint8Array(64)
  nonceInput.set(digest.subarray(32), 0)
  nonceInput.set(bigIntToBytesLE32(message), 32)
  const r = bytesToBigIntLE(blake512(nonceInput)) % SUBGROUP_ORDER

  // `r` is secret — leaking it leaks the private key — so use the
  // constant-time ladder here too.
  const R8 = BASE8.multiply(r).toAffine()
  const A = publicKey.toAffine()
  const challenge = poseidonPermute([R8.x, R8.y, A.x, A.y, message])[0]!

  return { R8, S: (r + challenge * scalar) % SUBGROUP_ORDER }
}

/**
 * Verify an EdDSA-Poseidon signature.
 *
 * Verification is cofactored: `S·B == R8 + (8·h)·A`. It is expressed as
 * `h·(8A)` because `8A` is guaranteed torsion-free, which makes reducing `h`
 * modulo the subgroup order exact. Reducing `8·h` directly would depend on
 * noble's `Fn.ORDER` convention, which differs between major versions.
 * @param message - Message as a BabyJubJub field element.
 * @param signature - Signature commitment and scalar.
 * @param signature.R8 - Signature commitment point.
 * @param signature.S - Signature scalar, required to be in `[0, L)`.
 * @param publicKey - Signer's public key.
 * @returns True when the signature is valid.
 */
const verifyPoseidon = (
  message: bigint,
  signature: { R8: Affine; S: bigint },
  publicKey: Affine
): boolean => {
  // Out-of-range S is a malleability vector: unchecked mod-L arithmetic would
  // let S ± kL verify the same message.
  if (signature.S < 0n || signature.S >= SUBGROUP_ORDER) return false

  const coordinates = [
    signature.R8.x, signature.R8.y, publicKey.x, publicKey.y,
  ]
  if (!coordinates.every(isCanonicalFieldElement)) return false

  let R8
  let A
  try {
    R8 = Point.fromAffine(signature.R8)
    R8.assertValidity()
    A = Point.fromAffine(publicKey)
    A.assertValidity()
  } catch {
    // Off-curve points are rejected, not surfaced as errors.
    return false
  }

  const challenge = poseidonPermute([
    signature.R8.x, signature.R8.y, publicKey.x, publicKey.y, message,
  ])[0]!

  const left = BASE8.multiplyUnsafe(signature.S)
  const right = R8.add(A.clearCofactor().multiplyUnsafe(challenge % SUBGROUP_ORDER))

  return left.equals(right)
}

export type { Affine }
export {
  derivePublicKey,
  signPoseidon,
  verifyPoseidon,
  SUBGROUP_ORDER,
  FIELD_MODULUS,
}
