import { bigIntToBytes, bytesToBigInt } from '@railgun-reloaded/bytes'

import {
  FIELD_MODULUS,
  SUBGROUP_ORDER,
  derivePublicKey,
  signPoseidon,
  verifyPoseidon,
} from './eddsa.js'

type EddsaSignature = {
  R8: [Uint8Array, Uint8Array];
  S: bigint;
}

// Order of the prime-order subgroup of BabyJubJub generated by Base8.
// A canonical EdDSA signature must have S ∈ [0, L). Out-of-range S is a
// signature-malleability vector — two distinct (R8, S) pairs verifying the
// same message — so we reject it at the wrapper boundary.
const BABYJUBJUB_SUBGROUP_ORDER = SUBGROUP_ORDER

/**
 * Reduce message bytes into the BabyJubJub base field as a big-endian integer.
 * @param message - Message bytes.
 * @returns The message as a field element in `[0, p)`.
 */
const messageToField = (message: Uint8Array): bigint =>
  bytesToBigInt(message) % FIELD_MODULUS

const eddsa = {
  /**
   * Convert a babyJubJub private key to its public key.
   * @param privateKey - 32-byte private key.
   * @returns The public key as a tuple of two 32-byte big-endian coordinates.
   */
  privateKeyToPublicKey (privateKey: Uint8Array): [Uint8Array, Uint8Array] {
    const { x, y } = derivePublicKey(privateKey)

    return [bigIntToBytes(x, 32), bigIntToBytes(y, 32)]
  },

  /**
   * Sign a message under the babyJubJub EDDSA scheme using Poseidon as the
   * hash function. The message bytes are interpreted as a big-endian field
   * element.
   * @param key - 32-byte private key.
   * @param message - Message bytes to sign.
   * @returns Signature as a 3-tuple `[R8x, R8y, S]`, each 32 bytes.
   */
  signPoseidon (
    key: Uint8Array,
    message: Uint8Array
  ): [Uint8Array, Uint8Array, Uint8Array] {
    const { R8, S } = signPoseidon(key, messageToField(message))

    return [
      bigIntToBytes(R8.x, 32),
      bigIntToBytes(R8.y, 32),
      bigIntToBytes(S, 32),
    ]
  },

  /**
   * Verify a babyJubJub EDDSA signature created with Poseidon. Signatures
   * whose `S` falls outside `[0, L)` are rejected as malleable, and any
   * malformed point (off-curve, identity, or small-subgroup) fails to verify.
   * @param message - Original message bytes.
   * @param signature - Signature decoded into `{ R8, S }` shape.
   * @param pubkey - Public key tuple matching the signing key.
   * @returns True when the signature verifies.
   */
  verifyEDDSA (
    message: Uint8Array,
    signature: EddsaSignature,
    pubkey: [Uint8Array, Uint8Array]
  ): boolean {
    return verifyPoseidon(
      messageToField(message),
      {
        R8: {
          x: bytesToBigInt(signature.R8[0]),
          y: bytesToBigInt(signature.R8[1]),
        },
        S: signature.S,
      },
      { x: bytesToBigInt(pubkey[0]), y: bytesToBigInt(pubkey[1]) }
    )
  },
}

export type { EddsaSignature }
export { eddsa, BABYJUBJUB_SUBGROUP_ORDER }
