import { PrivateKey, PublicKey, Signature } from '@iden3/js-crypto'
import { bigIntToBytes, bytesToBigInt } from '@railgun-reloaded/bytes'

type EddsaSignature = {
  R8: [Uint8Array, Uint8Array];
  S: bigint;
}

// Order of the prime-order subgroup of BabyJubJub generated by Base8.
// A canonical EdDSA signature must have S ∈ [0, L). Out-of-range S is a
// signature-malleability vector — two distinct (R8, S) pairs verifying the
// same message — so we reject it at the wrapper boundary.
const BABYJUBJUB_SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n

// Base field modulus of BabyJubJub. Messages are reduced into this field
// before hashing so that any byte length is accepted, matching the canonical
// scheme. Field-element messages (the only ones used in practice) are already
// in range, so the reduction is a no-op for them.
const BABYJUBJUB_FIELD_MODULUS =
  21888242871839275222246405745257275088548364400416034343698204186575808495617n

/**
 * Reduce message bytes into the BabyJubJub base field as a big-endian integer.
 * @param message - Message bytes.
 * @returns The message as a field element in `[0, p)`.
 */
const messageToField = (message: Uint8Array): bigint =>
  bytesToBigInt(message) % BABYJUBJUB_FIELD_MODULUS

const eddsa = {
  /**
   * Convert a babyJubJub private key to its public key.
   * @param privateKey - 32-byte private key.
   * @returns The public key as a tuple of two 32-byte big-endian coordinates.
   */
  privateKeyToPublicKey (privateKey: Uint8Array): [Uint8Array, Uint8Array] {
    const { p } = new PrivateKey(privateKey).public()

    return [bigIntToBytes(p[0], 32), bigIntToBytes(p[1], 32)]
  },

  /**
   * Sign a message under the babyJubJub EDDSA scheme using Poseidon as the
   * hash function. The message bytes are interpreted as a big-endian field
   * element.
   * @param key - 32-byte private key.
   * @param message - Message bytes to sign.
   * @returns Signature as a 3-tuple `[R8x, R8y, S]`, each 32 bytes.
   */
  signPoseidon (
    key: Uint8Array,
    message: Uint8Array
  ): [Uint8Array, Uint8Array, Uint8Array] {
    const signature = new PrivateKey(key).signPoseidon(messageToField(message))

    return [
      bigIntToBytes(signature.R8[0], 32),
      bigIntToBytes(signature.R8[1], 32),
      bigIntToBytes(signature.S, 32),
    ]
  },

  /**
   * Verify a babyJubJub EDDSA signature created with Poseidon. Signatures
   * whose `S` falls outside `[0, L)` are rejected as malleable, and any
   * malformed point (off-curve, identity, or small-subgroup) fails to verify.
   * @param message - Original message bytes.
   * @param signature - Signature decoded into `{ R8, S }` shape.
   * @param pubkey - Public key tuple matching the signing key.
   * @returns True when the signature verifies.
   */
  verifyEDDSA (
    message: Uint8Array,
    signature: EddsaSignature,
    pubkey: [Uint8Array, Uint8Array]
  ): boolean {
    if (signature.S < 0n || signature.S >= BABYJUBJUB_SUBGROUP_ORDER) return false

    try {
      const publicKey = new PublicKey([bytesToBigInt(pubkey[0]), bytesToBigInt(pubkey[1])])
      const sig = new Signature(
        [bytesToBigInt(signature.R8[0]), bytesToBigInt(signature.R8[1])],
        signature.S
      )

      return publicKey.verifyPoseidon(messageToField(message), sig)
    } catch {
      return false
    }
  },
}

export type { EddsaSignature }
export { eddsa, BABYJUBJUB_SUBGROUP_ORDER }
