import { bigIntToBytes } from '@railgun-reloaded/bytes'

import { assertEddsaReady } from './eddsa'

type CircomlibSignature = {
  R8: [Uint8Array, Uint8Array];
  S: bigint;
}

// Order of the prime-order subgroup of BabyJubJub generated by Base8.
// A canonical EdDSA signature must have S ∈ [0, L). Out-of-range S is a
// signature-malleability vector, and circomlibjs's verifyPoseidon
// infinite-loops on negative S — so we guard at the wrapper boundary.
// Source: iden3/circomlibjs babyjub.
const BABYJUBJUB_SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n

const eddsa = {
  /**
   * Convert a babyJubJub private key to its public key.
   * @param privateKey - 32-byte private key.
   * @returns The public key as a tuple of two 32-byte coordinates.
   * @throws CryptographyError(EddsaNotInitialized) if `initializeEddsa` has
   *         not been awaited.
   */
  privateKeyToPublicKey (privateKey: Uint8Array): [Uint8Array, Uint8Array] {
    const build = assertEddsaReady()
    const [x, y] = build.prv2pub(privateKey)

    return [
      build.F.fromMontgomery(x).reverse(),
      build.F.fromMontgomery(y).reverse(),
    ]
  },

  /**
   * Sign a message under the babyJubJub EDDSA scheme using Poseidon as the
   * hash function.
   * @param key - 32-byte private key.
   * @param message - Message bytes to sign.
   * @returns Signature as a 3-tuple `[R8x, R8y, S]`, each 32 bytes.
   * @throws CryptographyError(EddsaNotInitialized) if `initializeEddsa` has
   *         not been awaited.
   */
  signPoseidon (
    key: Uint8Array,
    message: Uint8Array
  ): [Uint8Array, Uint8Array, Uint8Array] {
    const build = assertEddsaReady()
    const montgomery = build.F.toMontgomery(new Uint8Array(message).reverse())
    const sig = build.signPoseidon(key, montgomery)
    const r8: [Uint8Array, Uint8Array] = [
      build.F.fromMontgomery(sig.R8[0]).reverse(),
      build.F.fromMontgomery(sig.R8[1]).reverse(),
    ]

    return [
      r8[0],
      r8[1],
      bigIntToBytes(sig.S, 32)
    ]
  },

  /**
   * Verify a babyJubJub EDDSA signature created with Poseidon.
   * @param message - Original message bytes.
   * @param signature - Signature decoded into `{ R8, S }` shape.
   * @param pubkey - Public key tuple matching the signing key.
   * @returns True when the signature verifies.
   * @throws CryptographyError(EddsaNotInitialized) if `initializeEddsa` has
   *         not been awaited.
   */
  verifyEDDSA (
    message: Uint8Array,
    signature: CircomlibSignature,
    pubkey: [Uint8Array, Uint8Array]
  ): boolean {
    const build = assertEddsaReady()
    if (signature.S < 0n || signature.S >= BABYJUBJUB_SUBGROUP_ORDER) return false
    const montgomery = build.F.toMontgomery(new Uint8Array(message).reverse())
    const r8: [Uint8Array, Uint8Array] = [
      build.F.toMontgomery(new Uint8Array(signature.R8[0]).reverse()),
      build.F.toMontgomery(new Uint8Array(signature.R8[1]).reverse()),
    ]
    const newPubKey: [Uint8Array, Uint8Array] = [
      build.F.toMontgomery(new Uint8Array(pubkey[0]).reverse()),
      build.F.toMontgomery(new Uint8Array(pubkey[1]).reverse()),
    ]

    return build.verifyPoseidon(montgomery, { R8: r8, S: signature.S }, newPubKey)
  },
}

export type { CircomlibSignature }
export { eddsa, BABYJUBJUB_SUBGROUP_ORDER }
